export enum TestIds {
  TimeRangeDropdown = 'TimeRangeDropdown',
  RefreshIntervalDropdown = 'RefreshIntervalDropdown',
  SyncButton = 'SyncButton',
  LogsHistogram = 'LogsHistogram',
  LogsTable = 'LogsTable',
  LogsMetrics = 'LogsMetrics',
  VolumeGraph = 'VolumeGraph',
  LogsQueryInput = 'LogsQueryInput',
  ExecuteQueryButton = 'ExecuteQueryButton',
  TenantDropdown = 'TenantDropdown',
  SeverityDropdown = 'SeverityDropdown',
  ToogleStreamingButton = 'ToogleStreamingButton',
  ShowQueryToggle = 'ShowQueryToggle',
  ShowStatsToggle = 'ShowStatsToggle',
  LogsStats = 'LogsStats',
  AttributeFilters = 'AttributeFilters',
  TimeRangeSelectModal = 'TimeRangeSelectModal',
  TimeRangeDropdownSaveButton = 'TimeRangeDropdownSaveButton',
  ToggleHistogramButton = 'ToggleHistogramButton',
}
